### PR TITLE
Adds Search Bar and Autocomplete Functionality

### PR DESCRIPTION
**Pull request by Step7750**
* Adds Search Bar toggle to header
* On desktop, presents the search bar in the header, on mobile it opens a dialog (due to lack of space)
* Creates SearchService that hooks up to the autocomplete backend
* Uses autocomplete results to populate autocomplete for the input

Some side effects
* Fixes utils.isMobile reference for the side nav, it now changes the mode when mobile
* Fixes utils.isMobile reference for the top margin of the content when mobile
* Renames the site title in the header to "MP" on mobile devices for more header space

Continues progress on #10

### CODE REVIEW

**Comment by Step7750** [comment]
Screenshots:

Mobile:
image

Desktop without Toggle:
image

Desktop w/ toggle and input:
image

**Comment by Step7750** [comment]
@xiningchen Thoughts on the styling?

**Comment by Step7750** [comment]
@xiningchen I've made the search bar expand by default on desktop.

The little `x` in the input when typing is automatically added by the browser when using `type=search`  for the input. If we remove that, the browser may handle it improperly: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

There is no built in option to offset a Material2 dialog AFAIK. I don't think it is worth the potential hack to make that work given how it could break if the library updates.

**Comment by xiningchen** [comment]
I think this can be merged.

**Pull request merged**
